Add annotation on PHP version failure

diff --git a/.github/workflows/compile-and-test.yml b/.github/workflows/compile-and-test.yml
--- a/.github/workflows/compile-and-test.yml
+++ b/.github/workflows/compile-and-test.yml
@@ -51,12 +51,16 @@ jobs:
       env:
         PHP_VERSION: "${{ github.event.inputs.phpversion }}"
       run: |
+        sudo apt-get update -qq
         if [ "$PHP_VERSION" = "distro" ]; then
           PHP_SUFFIX=""
         else
           PHP_SUFFIX="$PHP_VERSION"
         fi
-        sudo apt-get install -qq "php$PHP_SUFFIX" "php$PHP_SUFFIX-dev" libperl-dev
+        if ! sudo apt-get install -qq "php$PHP_SUFFIX" "php$PHP_SUFFIX-dev" libperl-dev; then
+          echo "::error::Failed to install PHP $PHP_VERSION"
+          exit 1
+        fi
         if [ "$PHP_VERSION" != "distro" ]; then
           sudo update-alternatives --set php "/usr/bin/php$PHP_VERSION"
           sudo update-alternatives --set phar "/usr/bin/phar$PHP_VERSION"
